version: "3.8"
services:
  postgres-db:
    image: postgres:16.4-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: temp_test_user
      POSTGRES_PASSWORD: test_userpassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j:community
    container_name: neo4j
    volumes:
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/config:/config
      - ./data/neo4j/data:/data
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/neo4j5025
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
    ports:
      - "7474:7474"
      - "7687:7687"

  age-graph:
    image: apache/age
    container_name: age-graph
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: temp_test_user
      POSTGRES_PASSWORD: test_userpassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/age-graph:/var/lib/postgresql/data
    ports:
      - "5455:5432"
